algoritmo "Estrutura-Para-Faça"
// Função :
// Autor :
// Data : 15/04/2020
// Seção de Declarações 
var
   numero, fatorial, contador: inteiro
inicio
      escreva("Digite o número para calcular o fatorial: ")
      leia(numero)
      
      fatorial:=1 // declara para começar com 1 para não começar com 0
      
      para contador de 1 ate numero faca
           fatorial:=fatorial * contador
      fimpara
      escreva("O fatorial de ", numero, " é: ", fatorial)
fimalgoritmo
