algoritmo "variaveis"

var
   nomeUtilizador: Caractere
   idadeUtilizador: Inteiro
   alturaUtilizador: Real
   estudante: Logico
inicio
      nomeUtilizador <- "João"
      idadeUtilizador <- 15
      alturaUtilizador <- 1.85
      estudante <- verdadeiro
      escreval("Nome: ",nomeUtilizador)
      escreval("Idade: ",idadeUtilizador)
      escreval("Altura: ",alturautilizador)
      escreval("Estudante: ",estudante )
fimalgoritmo
